# Generated by Django 3.0.2 on 2020-01-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greenery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strains', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('cannabinoids', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('feeling', models.CharField(max_length=120)),
                ('helpith', models.CharField(max_length=120)),
                ('Negatives', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
            ],
        ),
    ]
