# Generated by Django 3.0.2 on 2020-01-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenery', '0002_auto_20200131_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenery',
            old_name='cannabinoids',
            new_name='Cannabinoids',
        ),
        migrations.RenameField(
            model_name='greenery',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='greenery',
            old_name='feeling',
            new_name='Feeling',
        ),
        migrations.RenameField(
            model_name='greenery',
            old_name='helpith',
            new_name='HelpWith',
        ),
        migrations.RenameField(
            model_name='greenery',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='greenery',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='greenery',
            old_name='strains',
            new_name='Strains',
        ),
    ]
