# Generated by Django 3.0.2 on 2020-02-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenery', '0003_auto_20200131_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenery',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='greenery/'),
        ),
    ]
