# Generated by Django 3.0.2 on 2020-02-03 21:42

from django.db import migrations, models
import greenery.models


class Migration(migrations.Migration):

    dependencies = [
        ('greenery', '0005_auto_20200203_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenery',
            name='Image',
        ),
        migrations.AddField(
            model_name='greenery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=greenery.models.upload_image_path),
        ),
    ]
