# Generated by Django 3.0.2 on 2020-02-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenery', '0006_auto_20200203_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenery',
            old_name='image',
            new_name='Image',
        ),
    ]
