# Generated by Django 3.0.2 on 2020-02-03 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenery', '0007_auto_20200203_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenery',
            old_name='Image',
            new_name='image',
        ),
    ]
