# Generated by Django 3.0.2 on 2020-02-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenery', '0008_auto_20200203_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenery',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
