# Generated by Django 3.0.2 on 2020-02-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenery', '0011_auto_20200204_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenery',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
