# Generated by Django 3.0.2 on 2020-02-05 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('greenery', '0012_auto_20200204_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenery',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
